### ISSUE TITLE
SmartPublisherV2: 打开demo的界面报错InitRtspServer没有实现方法

### ISSUE THREAD

**Issue by bbbBBBSG** [daniulive/SmarterStreaming#89]
armeabi-v7a和x86都报相同的错
```
    java.lang.UnsatisfiedLinkError: No implementation found for int com.dahai.publishlivedemo.SmartPublisherJniV2.InitRtspServer(java.lang.Object) (tried Java_com_dahai_publishlivedemo_SmartPublisherJniV2_InitRtspServer and Java_com_dahai_publishlivedemo_SmartPublisherJniV2_InitRtspServer__Ljava_lang_Object_2)
        at com.dahai.publishlivedemo.SmartPublisherJniV2.InitRtspServer(Native Method)
        at com.dahai.publishlivedemo.CameraPublishActivity.onCreate(CameraPublishActivity.java:540)
        at android.app.Activity.performCreate(Activity.java:6301)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2530)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1499)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5765)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by daniulive** [comment]
对接请参看技术对接文档：视沃科技-大牛直播移动端SDK(V2)调用说明2.16.pdf
你这个报错，是因为 SmartPublisherJniV2.java 放到我们的包名下即可，调用的话，可以在其他包名下使用。
具体对接可以加群，或者加QQ 89030985 获取支持

> 确保SmartPublisherJniV2.java放到com.daniulive.smartpublisher包名下(可在其他包名下调用)；
Smartavengine.jar加入到工程；
拷贝SmartPublisherV2\app\src\main\jniLibs\armeabi-v7a、 SmartPublisherV2\app\src\main\jniLibs\arm64-v8a、SmartPublisherV2\app\src\main\jniLibs\x86 和SmartPublisherV2\app\src\main\jniLibs\x86_64下 libSmartPublisher.so到工程；
添加相关权限：
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" ></uses-permission>
<uses-permission android:name="android.permission.INTERNET" ></uses-permission>
<uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS" />
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
Load库:
		static {  
			System.loadLibrary("SmartPublisher");
	}
build.gradle配置32/64位库:
splits {
    abi {
        enable true
        reset()

        // Specifies a list of ABIs that Gradle should create APKs for
        //include "armeabi"
        include 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64' //select ABIs to build APKs for

        // Specify that we do not want to also generate a universal APK that includes all ABIs
        universalApk true
    }
}
如需集成到自己系统测试，请用大牛直播SDK的app name(不然集成提示license failed)，正式授权版按照授权app name正常使用即可；
如何改app-name：
strings.xml做以下修改：
<string name="app_name">SmartPublisherSDKDemo</string>
